### ISSUE TITLE
Hub-kids

### ISSUE THREAD

**Issue by giapponesetimido** [Leone25/hub-young-downloader#6]
I thank you for all your works, they works at all! I wanna ask you how to download books from hub-kids. The container "Hub Scuola" is the same but if a book is from primary school becomes hub-kids.
Thank you, I appreciate so much.
Have a nice day

**Comment by Leone25** [comment]
well i do not have any books i could test against, but i'm sure it can be made

**Comment by ghost** [comment]
UPDATE: i managed to do it! Just replace "young" with "kids" in the code...

**Comment by Leone25** [comment]
Support has been added, closing this.
