### ISSUE TITLE
SyntaxError: Unexpected token N in JSON at position 0

### ISSUE THREAD

**Issue by ntho6** [Leone25/hub-young-downloader#8]
It gives me this error, why?

SyntaxError: Unexpected token N in JSON at position 0
    at JSON.parse (<anonymous>)
    at Response.json (file:///C:/Users/Utente/Desktop/hub-young-downloader-main/node_modules/node-fetch/src/body.js:149:15)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async file:///C:/Users/Utente/Desktop/hub-young-downloader-main/index.js:46:22

Node.js v18.12.1

**Comment by Leone25** [comment]
probably something is wrong and the server is returning not found which is causing the json parser to error out

**Comment by ntho6** [comment]
Oh, Is there anything I can do to fix this error?

**Comment by Leone25** [comment]
honestly I'm not quite sure, I tried it my self and everything seems to be working so perhaps you imputed something wrong? if not then there is a need to explore further

**Comment by ntho6** [comment]
I tried on another device with the last Node.js version but it doesn't seem to work :(

**Comment by Leone25** [comment]
Please dm me on twitter (same name + 03l so that i can help you better
