### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by GabrieleDev6** [Leone25/hub-young-downloader#9]
When I run this program I get this error:

Obtaining volume info . . .
(node:23880) UnhandledPromiseRejectionWarning: SyntaxError: Unexpected token N in JSON at position 0
    at JSON.parse (<anonymous>)
    at Response.json (file:///C:/Users/Gabriele/Desktop/hub-young-downloader-main/node_modules/node-fetch/src/body.js:149:15)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async file:///C:/Users/Gabriele/Desktop/hub-young-downloader-main/index.js:46:22
(Use `node --trace-warnings ...` to show where the warning was created)
(node:23880) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:23880) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by Leone25** [comment]
Hi, generally that error means you did something wrong.

If that is not the case please dm me on twitter (same name + 03) so that i can handle this more privately

**Comment by goldmont** [comment]
Hi, what Node version are you using? Just tested with Node `v16.19.0` and it works just fine.
